### ISSUE TITLE
parameters question?

### ISSUE THREAD

**Issue by crankler** [wangx1996/Lidar-Segementation#1]
你好, 能否请教下你CVC这篇文章中的相关参数选择问题?
1.deltaR, deltaP, width的选择实际是怎么考虑的呢?

```
    length = round((maxrange - minrange)/deltaR);
    width = 301; //?
    height = round((maxazimuth - minazimuth)/deltaA);
```

2.求取最大的三个索引的目的在于哪?
```
    auto maxPosition = max_element(ai.begin(), ai.end());
    auto maxPosition1 = max_element(ri.begin(), ri.end());
    auto maxPosition2 = max_element(pi.begin(), pi.end());
```

3. 求取azimuth_index有两种不同方法:
    //   int azimuth_index = round((vapr[i].azimuth+fabs(minazimuth))*180/PI/deltaA);
    //   int azimuth_index = round(((vapr[i].azimuth-minazimuth)*180/PI)/deltaA);

谢谢回复!

**Comment by wangx1996** [comment]
> 你好, 能否请教下你CVC这篇文章中的相关参数选择问题?
> 1.deltaR, deltaP, width的选择实际是怎么考虑的呢?
> 
> ```
>     length = round((maxrange - minrange)/deltaR);
>     width = 301; //?
>     height = round((maxazimuth - minazimuth)/deltaA);
> ```
> 
> 2.求取最大的三个索引的目的在于哪?
> 
> ```
>     auto maxPosition = max_element(ai.begin(), ai.end());
>     auto maxPosition1 = max_element(ri.begin(), ri.end());
>     auto maxPosition2 = max_element(pi.begin(), pi.end());
> ```
> 
> 1. 求取azimuth_index有两种不同方法:
>    //   int azimuth_index = round((vapr[i].azimuth+fabs(minazimuth))*180/PI/deltaA);
>    //   int azimuth_index = round(((vapr[i].azimuth-minazimuth)*180/PI)/deltaA);
> 
> 谢谢回复!

你好：
1.相关参数的选择主要是依据传感器的基本参数决定的，主要是包括激光雷达的垂直角分辨率以及横向角分辨率，这里的width指的是水平面扇形区域的划分，我这里把它进行了一个固定，也就是默认取得的水平分辨率为1.2度，这个是可以更改的；
2.这个最大索引相当于是一个打印结果的功能，因为在点云聚类之前还需要进行一系列的操作如地面滤除，范围选择等，这里打印这三个参数就只是看一下我网格划分的范围大小；
3.这两个函数从目前我所用的数据来看是一样的，因为最小的azimuth是一定小于0的，所以这里用的减法和取绝对值相加的效果是一样的，不过更建议用第二种

**Comment by crankler** [comment]
非常感谢回复,!
关于参数问题: 我将代码中的301修改成 round((360/deltaP)), 类似legoloam那样, 其余问题懂了.谢谢!

最近几天我尝试修改cvc和dbscan,rbnn的聚类方法,通过数据集进行测试后发现,,CVC的聚类效果感觉不是很好啊(尝试用高通滤波去除地面后,我尝试调整deltaR,deltaP,deltaA)
之后我在一个搭建的gazebo仿真环境中进行测试,我发现cvc存在把有一定聚类的具体划分成同一标签的现象
对了,我仅仅加了个ros框架,然后尝试的测试,不知道这样是否正确, 能够交流下测试经验吗?谢谢!

**Comment by wangx1996** [comment]
> 非常感谢回复,!
> 关于参数问题: 我将代码中的301修改成 round((360/deltaP)), 类似legoloam那样, 其余问题懂了.谢谢!
> 
> 最近几天我尝试修改cvc和dbscan,rbnn的聚类方法,通过数据集进行测试后发现,,CVC的聚类效果感觉不是很好啊(尝试用高通滤波去除地面后,我尝试调整deltaR,deltaP,deltaA)
> 之后我在一个搭建的gazebo仿真环境中进行测试,我发现cvc存在把有一定聚类的具体划分成同一标签的现象,感觉不如dbscan啊!
> 
> 对了,我仅仅加了个ros框架,然后就是尝试修改了那三个参数, 之后尝试的测试,不知道这样是否正确,
> 能够交流下测试经验吗?谢谢!

这个方法整体来讲效果确实不够理想，主要取决于那三个参数的选择，相较于dbscan而言就是速度上稍快，可以尝试用作分阶段聚类里的一个阶段，但是这些基于传统的调节参数的聚类方法多少都不会有特别好的效果

**Comment by crankler** [comment]
这么说也对，传统的这些方法基本上效果全靠调参，且效果不是很好
谢谢最近的回复与分享！
