### ISSUE TITLE
License for reuse of code

### ISSUE THREAD

**Issue by Omar-Tag** [wangx1996/Lidar-Segementation#4]
First of all , I would like to express appreciation and admire to your work in the GitHub repository towards your implementation of some of the state of the art published papers contributing to the perception field .

i wanted kindly inquire about the availability of a **license** for the open source repo “Lidar Segmentation” , for example an "**MIT** " license ? . I was mostly interested in the rights to use the implementation part regarding clustering approach from “Curved-Voxel Clustering for Accurate Segmentation of 3D LiDAR Point Clouds with Real-Time Performance'

It would gladly be helpful to have a license for this project as I am working on R&D project and would like to appropriately know the rights to use your published software code.

**Comment by wangx1996** [comment]
@Omar-Tag First of all ,thank you for your interest in this project. And I didn't pay too much attention on the license before. Now I  add a MIT license for this project, and I think it would be helpful for you.
